repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
        args:
          - --line-length=79

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
        args: ['--config-file', 'mypy.ini']
        exclude: ^migrations/|/migrations/