# Generated by Django 5.1.4 on 2024-12-23 19:01

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LangchainPgCollection",
            fields=[
                ("name", models.CharField(blank=True, null=True)),
                ("cmetadata", models.TextField(blank=True, null=True)),
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "langchain_pg_collection",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LangchainPgEmbedding",
            fields=[
                (
                    "embedding",
                    pgvector.django.vector.VectorField(dimensions=1536),
                ),
                ("document", models.CharField(blank=True, null=True)),
                ("cmetadata", models.TextField(blank=True, null=True)),
                ("custom_id", models.CharField(blank=True, null=True)),
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "langchain_pg_embedding",
                "managed": False,
            },
        ),
    ]
